### PR TITLE
Update  header value only if he doesn't exist

### PR DESCRIPTION
**Pull request by Matsa59**

### CODE REVIEW

**Comment by NicolasGeraud** [comment]
hi @Matsa59 
I don't understand why you need that ?

Because we transform json to json, the content type must be `application/json` no ?

**Comment by Matsa59** [comment]
In fact it break some system like Mime versioning. It should not update the `Content-Type` or just define it if it's empty (that's what I do in my PR)

e.g.
```
Content-Type: application/vnd.myname.v1.4.2+json
// or
Accept: application/vnd.myname.v1.4.2+json
```

**Comment by NicolasGeraud** [comment]
The problem is, with this PR, we change the behavior of the policy. In current gravitee deployment, perhaps backend send plan/text and this policy change the content-type.

It's the same thing from the consumer point of view ...

In your use case, the transformation inside the json2json does not change the version of the api you need to request, right ?

**Comment by Matsa59** [comment]
I agree with you, that's why you can use the transform header policy.

> In your use case, the transformation inside the json2json does not change the version of the api you need to request, right ?

Maybe I don't understand but in the case of you use gravitee only for the gateway (rate limite / docs / keys) and the version is manage by the API you will have a bad behavior : 

Client -> Gateway
```
GET : /api/clients
Headers: 
- Content-Type: application/vnd.myname.v1.4.2+json
```

Gateway -> API
```
GET : /clients
Headers: 
- Content-Type: application/json
```
> The API should match the `Content-Type` type to define which transformer (json to object) must be used.

--- 

Api -> Gateway
```
GET : /api/clients
Headers: 
- Content-Type: application/vnd.myname.v1.4.2+json
```

Gateway -> Client
```
GET : /clients
Headers: 
- Content-Type: application/json
```
> If the client can manage multiple version of the API he will not be able to define with schema is used. By default he should use the last but his last can be different than the last server version.

In some case, client can send a mime version that does not exist. The client will not be notify. 
> Eg. I ask for the version 3.0.0 and the available versions are : 1.0.0, 2.0.0, 2.1.0. The server will return a `content-type` equal to `application/json` so what? Everything works well, I got the version 3.0.0? In this case I don't know and because I got exactly what I ask I will not change my code. Some times later, version 3.0.0 is release and all my program crash because I ask a version that have major changes.

**Comment by NicolasGeraud** [comment]
ok, so here is a compromise that feat your needs and preserve the actual behavior of the policy.

You could add an boolean in the configuration : 
```
//by default, we override the content-type to be backward compatible
private boolean overideContentType = true;
```

with this in the schema-form.json : 
```
"overideContentType" : {
      "title": "Override the Content-Type",
      "description": "Enforce the Content-Type: application/json",
      "type" : "boolean",
      "default": true
    },
```

And in your code, if the override is true, you set the content-type to `application/json`, else, you apply your code (use the existing content type if exists or `application/json` by default.

What do you think ?

**Comment by brasseld** [comment]
🕐  tic tac tic tac 🕐 

Release 1.13 is scheduled for next tuesday. If you want to get this feature in next version, you know what you have to do ;)

Cheeeers

**Comment by Matsa59** [comment]
Ok working on, I should update the PR tonight.
See you ;)

**Comment by NicolasGeraud** [comment]
hi @Matsa59 
it seems that your night is long :)

any update ?

**Comment by NicolasGeraud** [comment]
@Matsa59 no news ?

**Comment by NicolasGeraud** [comment]
I close this issue.
If someone want to work on it, please, reopen it.

**Pull request closed without merging**
